FROM node:17-bullseye
RUN git clone https://github.com/caskel/uptime-kuma.git && cd uptime-kuma \
&& npm install && npm install pm2 -g && pm2 install pm2-logrotate && \
pm2 startup &&  npm run setup && \
pm2 start server/server.js --name uptime-kuma -- --port=8080
